# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ouWdD_hfb8hSlpNdJSdN2vI-KHk5Uwye
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np          # importamos numpy como np
import pandas as pd         # importamos pandas como pd
import math
import random
import warnings
# Ignorar advertencias de convergencia para los modelos lineales
warnings.filterwarnings('ignore', category=UserWarning, module='sklearn')

# Cargamos módulos de análisis gráficos
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns
sns.set_theme(style = 'whitegrid')
# %config InlineBackend.figure_format = 'retina'

# Preprocesado
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
# División muestras
from sklearn.model_selection import train_test_split

# Modelos de clasificación
from sklearn.linear_model import LogisticRegression, RidgeClassifier, LinearRegression, Lasso, Ridge
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.svm import SVC, SVR
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor, GradientBoostingRegressor
from lightgbm import LGBMClassifier, LGBMRegressor
from xgboost import XGBClassifier, XGBRegressor

# métricas de clasificación
from sklearn.metrics import accuracy_score, precision_score, balanced_accuracy_score, f1_score, recall_score
from sklearn.metrics import roc_auc_score, roc_curve, classification_report, confusion_matrix, ConfusionMatrixDisplay

def reports_clas(modelo, xtrain, ytrain, xtest, ytest,labels=None):
  '''
  Función para obtener el report de clasificación para un modelo de clasifcación. Porpociona los resultados para la muestra de entrenamiento y test

  Argumentos:
  - modelo: modelo entrenado
  - xtrain: inputs de entrenamiento
  - ytrain: target de entrenamiento
  - xtest: inputs de test
  - ytest: target de test
  - labels: Lista de etiquetas para el classification_report y la matriz de confusión.
              Si es None, se usarán las etiquetas por defecto de classification_report.

  Return
   - reporte de clasificación para muestra de entrenamiento y test
  '''
  from sklearn.metrics import classification_report

  clase_train = modelo.predict(xtrain)
  clase_test = modelo.predict(xtest)
  print("Métricas de clasificación en la muestra de entrenamiento")
  print(classification_report(ytrain, clase_train,labels=labels,zero_division=0))
  print("\n Métricas de clasificación en la muestra test")
  print(classification_report(ytest, clase_test,labels=labels,zero_division=0))

def matriz_confusion(modelo, xtest, ytest,labels=None):
  '''
  Matriz de confusion de un modelo de clasificacion en % de acierto dentro de cada
  clase real (normalizada por fila). Robusta a clases sin muestras (evita /0).

  Argumentos: modelo entrenado, xtest, ytest. Return: matriz normalizada (np.array).     
     - labels: Lista de etiquetas para el classification_report y la matriz de confusión.
              Si es None, se usarán las etiquetas por defecto de classification_report.
  '''
  from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
  cm = confusion_matrix(ytest, modelo.predict(xtest), labels=modelo.classes_).astype(float)
  fila = cm.sum(axis=1, keepdims=True)
  cmn = np.divide(cm, fila, out=np.zeros_like(cm), where=fila != 0)
  ConfusionMatrixDisplay.from_estimator(modelo, xtest, ytest, cmap='Blues', ax=ax, values_format='.1%', display_labels=labels)
  plt.grid(False); plt.title('Matriz de confusion (% por clase real)'); plt.show()
  return cmn

from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.metrics import f1_score, precision_score, recall_score
def validar_modelo(modelo, xtrain, ytrain, score, folds):
    '''
    Validacion cruzada respecto a un score. Devuelve el score por fold (DataFrame)
    e imprime media +/- desviacion.

    Argumentos: modelo, xtrain, ytrain, score ('accuracy','precision','recall','f1','roc_auc'...), folds.
    '''
    # Se genera el objeto StratifiedKFold
    # En clasificacion siempre es mejor usar StratifiedKFold
    cv = StratifiedKFold(n_splits=folds, shuffle=True, random_state=42)
    # Determinar si es un problema de clasificación multiclase
    is_multiclass = ytrain.nunique() > 2
    # Ajustar el parámetro 'average' para métricas multiclase si es necesario
    scoring_metric = score
    if is_multiclass and score in ['f1', 'precision', 'recall']:
        scoring_metric = f'{score}_weighted'
    # Calculamos la validación cruzada para cada fold
    cv_results = cross_val_score(modelo, xtrain, ytrain, cv=cv, scoring=scoring_metric, n_jobs=-1)
    # Creamos un DataFrame con los resultados
    df_results = pd.DataFrame({'fold': range(1, folds + 1), 'score': cv_results})
    # Imprimimos la media y la desviación estándar
    print(f"Validacion cruzada ({folds} folds, score={score}): media = {np.mean(cv_results):.3f} +/- {np.std(cv_results):.3f}")
    return df_results

def curva_aprendizaje(modelo, X, y, score, folds):
  '''
  Curva de aprendizaje: dibuja la puntuacion en ENTRENAMIENTO y en VALIDACION
  (con bandas de desviacion) frente al tamano de muestra, para diagnosticar
  sesgo/varianza (sobre/infra-ajuste).

  Argumentos: modelo, X, y, score, folds. Return: (train_sizes, train_mean, val_mean).
  '''
  from sklearn.model_selection import learning_curve
  sizes = np.linspace(0.2, 1.0, 8)
  ts, tr, te = learning_curve(modelo, X, y, train_sizes=sizes, scoring=score, cv=folds)
  trm, trs = tr.mean(1), tr.std(1); tem, tes = te.mean(1), te.std(1)
  plt.figure(figsize=(7, 5))
  plt.plot(ts, trm, 'o-',  color='steelblue', label='entrenamiento')
  plt.fill_between(ts, trm-trs, trm+trs, alpha=.15, color='steelblue')
  plt.plot(ts, tem, 'o--', color='red', label='validacion')
  plt.fill_between(ts, tem-tes, tem+tes, alpha=.15, color='red')
  plt.xlabel('n muestras de entrenamiento'); plt.ylabel(f'score ({score})')
  plt.title('Curva de aprendizaje'); plt.legend(); plt.grid(True); plt.show()
  return ts, trm, tem

def select_variables(modelo, X, y, k_values, score, folds=10):
    """
    Selecciona las k mejores caracteristicas con Eliminacion Recursiva (RFE) y
    validacion cruzada SIN fuga de informacion: la RFE se ajusta dentro de cada
    particion (mediante un Pipeline). Devuelve (scores_df, variables, k_best, score_best).
    """
    from sklearn.feature_selection import RFE
    from sklearn.model_selection import cross_val_score
    from sklearn.pipeline import Pipeline
    filas, best = [], (-float('inf'), None)
    for k in k_values:
        if k > X.shape[1]:
            print(f"Cuidado: k={k} es mayor que el numero de columnas de X ({X.shape[1]}).")
            continue
        pipe = Pipeline([('rfe', RFE(modelo, n_features_to_select=k)), ('clf', modelo)])
        m = cross_val_score(pipe, X, y, cv=folds, scoring=score).mean()
        filas.append({'k': k, 'score': m})
        if m > best[0]:
            best = (m, k)
    sel = RFE(modelo, n_features_to_select=best[1]).fit(X, y)
    variables = X.columns[sel.support_].tolist()
    return pd.DataFrame(filas), variables, best[1], best[0]
    
def podar_tree_clf(modelo,xtrain,ytrain,xtest,ytest):
  '''
  Función para llevar a cabo la poda de un árbol de decisión

  Argumentos:
    - modelo: modelo de árbol de decisión
    - xtrain: muestras de entrenamiento
    - ytrain: etiquetas de entrenamiento
    - xtest: muestras de test
    - ytest: etiquetas de test

  Devuelve:
    Imprimer el valor de alpha óptimo y devuelve el árbol podado
  '''
  from sklearn import tree
  from sklearn.tree import DecisionTreeClassifier
  
  # Identificamos los valores alpha e impurezas
  path = modelo.cost_complexity_pruning_path(xtrain, ytrain)
  # extraer diferentes valores de alpha (y excluimos el del árbol trivial)
  ccp_alphas = path.ccp_alphas[:-1]
  # creamos un array donde introduciremos los árboles de decisión
  clfs = []
  # creamos un árbol de decisión por cada valor de alpha y lo guardamos
  for ccp_alpha in ccp_alphas:
    clf = DecisionTreeClassifier(random_state = 0, ccp_alpha = ccp_alpha)
    clf.fit(xtrain, ytrain)
    clfs.append(clf)
  # Obtenemos la exactitud en las muestras train/test
  train_scores = [clfsco.score(xtrain, ytrain) for clfsco in clfs]
  test_scores = [clfsco.score(xtest, ytest) for clfsco in clfs]
  # guardamos todos los resultados
  poda = pd.DataFrame(np.stack([ccp_alphas,
              np.array(train_scores),
              np.array(test_scores)],axis=1),
             columns= ["alpha", "score_train", "score_test"])
  # identificamos la exactitud máxima en la muestra test
  pos = poda.idxmax(axis=0).score_test
  # Valores óptimos
  print(f"Valor óptimo de alpha: {poda.iloc[pos,0]:.4f}")
  print(f"Score muestra de entrenamiento: {poda.iloc[pos,1]:.4f}")
  print(f"Score muestra de test: {poda.iloc[pos,2]:.4f}")

  modelofinal = DecisionTreeClassifier(random_state=0,ccp_alpha=poda.iloc[pos,0])
  return(modelofinal)

def plot_importancias(modelo):
  '''
  Función para obtener las importancias de los inputs de un modelo

  Argumentos:
  - modelo: modelo entrenado

  Devuelve:
  - Imprime matriz de importancia y devuleve el gráfico asociado
  '''
  matriz_importancia= pd.DataFrame([modelo.feature_importances_],
             index = ["importancia"],
             columns = modelo.feature_names_in_).T
  matriz_importancia.sort_values(by='importancia',ascending=False,inplace=True)
  print("Matriz de importancias")
  print(matriz_importancia)
  matriz_importancia.plot.barh();

def grafico_prediccion(modelo, xtest, ytest):
    """
    Genera un gráfico de dispersión comparando los valores reales (ytest)
    contra los valores predichos por el modelo.

    Parámetros:
    - modelo: El modelo ya entrenado (ej. LinearRegression).
    - xtest: Datos de características para prueba.
    - ytest: Etiquetas reales correspondientes a xtest.
    """
    # 1. Generar las predicciones
    ypred = modelo.predict(xtest)

    # 2. Configurar el tamaño de la figura
    plt.figure(figsize=(8,8))

    # 3. Crear el gráfico de dispersión (Scatter Plot)
    # alpha=0.6 ayuda a ver dónde se concentran los datos si hay muchos puntos solapados
    plt.scatter(ypred, ytest, alpha=0.6, color='royalblue', edgecolor='k', s=50)

    # 4. Añadir línea de referencia (Identidad perfect y=x)
    # Calculamos el mínimo y máximo global para trazar la línea diagonal completa
    min_val = min(np.min(ytest), np.min(ypred))
    max_val = max(np.max(ytest), np.max(ypred))
    plt.plot([min_val, max_val], [min_val, max_val], 'r--', linewidth=2, label='Predicción Perfecta')

    # 5. Etiquetas y Títulos
    plt.xlabel('Valor Predicho', fontsize=12)
    plt.ylabel('Valor Real', fontsize=12)
    plt.title('')
    plt.legend()
    plt.grid(True, linestyle=':', alpha=0.6)

    # Mostrar gráfico
    plt.show()

import scipy.stats as stats
from sklearn.metrics import mean_squared_error, r2_score

def evaluar_modelo_regresion(modelo, xtrain, ytrain, xtest, ytest):
    """
    Calcula y devuelve un DataFrame con RMSE, R2 Ajustado, F-statistic, P-valor,
    AIC y BIC comparando los conjuntos de Train y Test.

    Parámetros:
    - modelo: El modelo ya entrenado.
    - xtrain: Datos de características para train.
    - ytrain: Etiquetas reales correspondientes a xtrain.
    - xtest: Datos de características para test.
    - ytest: Etiquetas reales correspondientes a xtest.
    """

    resultados = {}

    # Iteramos sobre los dos conjuntos (Train y Test)
    datas = [('Train', xtrain, ytrain), ('Test', xtest, ytest)]

    for nombre, x, y in datas:
        # 1. Predicciones
        ypred = modelo.predict(x)

        # 2. Variables auxiliares
        n = len(y)          # Número de observaciones
        p = x.shape[1]      # Número de predictores

        # 3. RMSE
        mse = mean_squared_error(y, ypred)
        rmse = np.sqrt(mse)

        # 4. R2 y R2 Ajustado
        r2 = r2_score(y, ypred)
        r2_adj = 1 - (1 - r2) * (n - 1) / (n - p - 1)

        # 5. Estadístico F y P-valor
        if r2 > 0 and r2 < 1:
            f_stat = (r2 / p) / ((1 - r2) / (n - p - 1))
            p_val = stats.f.sf(f_stat, p, n - p - 1)
        else:
            f_stat = np.nan
            p_val = np.nan

        # 6. AIC y BIC
        # Cálculo manual basado en la Log-Verosimilitud aproximada usando MSE
        # k = número de parámetros (predictores + intercepto)
        k = p + 1

        # Fórmula: AIC = n * ln(MSE) + 2k
        aic = n * np.log(mse) + 2 * k

        # Fórmula: BIC = n * ln(MSE) + k * ln(n)
        bic = n * np.log(mse) + k * np.log(n)

        # Guardamos en el diccionario (Asegurando que coincida con el índice de abajo)
        resultados[nombre] = [rmse, r2_adj, p_val, aic, bic]

    # Crear DataFrame
    indices = [
        'RMSE',
        'R2 Ajustado',
        'P-Valor F-Stat',
        'AIC',
        'BIC'
    ]

    df_metricas = pd.DataFrame(resultados, index=indices)
    return df_metricas

from sklearn.model_selection import cross_val_score
from sklearn.metrics import make_scorer, mean_squared_error, r2_score

def validar_modelo_regresion(modelo, xtrain, ytrain, score, folds):
    '''
    Función que proporciona un análisis de validación cruzada para regresión 
    con respecto a un score de evaluación.

    Argumentos de entrada:
    - modelo: modelo instanciado o entrenado (sklearn estimator)
    - xtrain: inputs de entrenamiento (DataFrame o numpy array)
    - ytrain: target de entrenamiento
    - score: métrica de evaluación ('r2', 'rmse', 'r2_ajustado', 'neg_mean_absolute_error', etc.)
    - folds: número de folds de validación cruzada

    Return:
    - tabla (DataFrame) con el análisis descriptivo de la validación cruzada
    '''

    # 1. Definimos las funciones de métricas personalizadas
    # Es importante definirlas dentro para que capturen el contexto si fuera necesario
    
    def rmse_calc(y_true, y_pred):
        """Calcula Root Mean Squared Error"""
        return np.sqrt(mean_squared_error(y_true, y_pred))

    def r2_adj_calc(y_true, y_pred):
        """Calcula R2 Ajustado"""
        n = len(y_true)
        # Obtenemos p (número de predictores) de la variable xtrain pasada a la función padre
        p = xtrain.shape[1] 
        r2 = r2_score(y_true, y_pred)
        return 1 - (1 - r2) * (n - 1) / (n - p - 1)

    # 2. Determinamos la estrategia de scoring
    if score == 'rmse':
        # Creamos un scorer que devuelva el error positivo
        scorer = make_scorer(rmse_calc) 
        nombre_metrica = "RMSE"
        
    elif score == 'r2_ajustado':
        # Creamos el scorer para R2 ajustado
        scorer = make_scorer(r2_adj_calc)
        nombre_metrica = "R2 Ajustado"
        
    else:
        # Si no es personalizado, usamos el string de scikit-learn (ej: 'r2', 'neg_mean_squared_error')
        scorer = score 
        nombre_metrica = score

    # 3. Ejecución de la Validación Cruzada
    try:
        cv_scores = cross_val_score(estimator=modelo, 
                                    X=xtrain, 
                                    y=ytrain, 
                                    cv=folds, 
                                    scoring=scorer)
    except ValueError as e:
        return f"Error al ejecutar cross_val_score. Verifica la métrica o los datos: {e}"

    # 4. Formateo de resultados
    # Convertimos a DataFrame para usar .describe()
    score_val = pd.DataFrame(cv_scores, columns=[nombre_metrica])
    
    # Obtenemos las estadísticas descriptivas y transponemos
    tabla_resultado = score_val.describe().T.round(4)
    print(f"--- Análisis de Validación Cruzada ({folds} folds) ---")
    print(f"Métrica utilizada: {nombre_metrica}")
    display(tabla_resultado)


import pandas as pd
import numpy as np
from sklearn.feature_selection import RFE
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error

def select_variables_regresion(modelo, X, y, k_values, score):
    """
    1. Ordena todas las predictoras por importancia usando RFE.
    2. Evalúa iterativamente los modelos incrementando k.
    3. Devuelve las variables ordenadas de mayor a menor importancia según RFE.

    Args:
        modelo: modelo de regresión.
        X (pd.DataFrame): matriz de inputs.
        y (pd.Series): vector de target.
        k_values (list): lista de valores de k a probar.
        score (str): métrica para optimizar ('rmse', 'aic', 'bic').

    Returns:
        tupla: 
            - pd.DataFrame: Tabla con k, métricas y variables acumuladas.
            - list: Las mejores variables ORDENADAS por importancia.
            - int: k óptimo.
            - float: score óptimo.
    """
    
    # Validación del score
    valid_scores = ['rmse', 'aic', 'bic']
    if score not in valid_scores:
        raise ValueError(f"El parámetro 'score' debe ser uno de: {valid_scores}")

    print("Calculando el ranking global de variables (puede tardar un momento)...")
    
    # 1. OBTENER EL ORDEN DE IMPORTANCIA GLOBAL (Ranking)
    # Al pedirle que seleccione 1, RFE calculará el ranking de eliminación de TODAS.
    # La variable con ranking 1 es la última en ser eliminada (la más importante).
    rfe_global = RFE(modelo, n_features_to_select=1)
    rfe_global.fit(X, y)

    # Creamos un DataFrame para ordenar las variables según su ranking RFE
    mapa_ranking = pd.DataFrame({
        'Variable': X.columns,
        'Ranking': rfe_global.ranking_
    }).sort_values('Ranking') # Orden ascendente: 1 (mejor), 2 (segunda), ...

    # Lista maestra ordenada de la más importante a la menos importante
    variables_ordenadas = mapa_ranking['Variable'].tolist()
    
    # -------------------------------------------------------------------------
    
    best_k = -1
    best_score = float('inf')
    best_features = None
    scores_list = []
    n = len(y)

    print(f"Evaluando combinaciones optimizando por: {score.upper()}...\n")

    # 2. EVALUACIÓN ITERATIVA SIGUIENDO EL ORDEN
    for k in k_values:
        if k > len(variables_ordenadas): continue

        # Seleccionamos las top k variables de la lista ya ordenada
        current_vars = variables_ordenadas[:k]
        X_new = X[current_vars]
        
        # --- CÁLCULO DE MÉTRICAS ---
        
        # A) RMSE (Validación Cruzada)
        cv_scores = cross_val_score(modelo, X_new, y, cv=10, scoring='neg_root_mean_squared_error')
        rmse_val = -cv_scores.mean()

        # B) AIC y BIC (Ajuste global)
        modelo.fit(X_new, y)
        ypred = modelo.predict(X_new)
        mse = mean_squared_error(y, ypred)
        num_params = k + 1 
        
        aic_val = n * np.log(mse) + 2 * num_params
        bic_val = n * np.log(mse) + num_params * np.log(n)

        # Guardamos métricas
        metrics = {
            'k': k, 
            'rmse': rmse_val, 
            'aic': aic_val, 
            'bic': bic_val,
            # Mostramos la última variable agregada para ver qué aporta
            'Nueva Variable': current_vars[-1] 
        }
        scores_list.append(metrics)

        # --- OPTIMIZACIÓN ---
        current_score_value = metrics[score]

        if current_score_value < best_score:
            best_score = current_score_value
            best_k = k
            # Guardamos la lista tal cual (ya está ordenada por importancia)
            best_features = current_vars

    scores_df = pd.DataFrame(scores_list)

    return scores_df, best_features, best_k, best_score

import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import learning_curve

def curva_aprendizaje_regresion(modelo, X, y, score, folds):
    '''
    Genera una curva de aprendizaje para modelos de regresión.
    Muestra cómo evoluciona la métrica de validación al aumentar el tamaño del set de entrenamiento.
    '''

    # 1. Configuración de la métrica
    if score == 'rmse':
        sklearn_score = 'neg_root_mean_squared_error'
    elif score == 'r2_ajustado':
        sklearn_score = 'r2'
    else:
        sklearn_score = score

    # --- CORRECCIÓN AQUÍ ---
    # Usamos linspace para asegurar que el máximo sea exactamente 1.0 y no 1.00000001
    # Esto genera 5 puntos equidistantes entre el 20% y el 100%
    sizes_prop = np.linspace(0.2, 1.0, 5) 

    # 2. Calcular curva de aprendizaje
    train_sizes_abs, train_scores, test_scores = learning_curve(
        modelo, 
        X, 
        y, 
        train_sizes=sizes_prop,
        scoring=sklearn_score,
        cv=folds,
        n_jobs=-1 
    )

    # 3. Procesamiento de resultados
    mean_test_scores = test_scores.mean(axis=1)

    if score == 'rmse':
        mean_test_scores = -mean_test_scores
        titulo_y = "RMSE (Menor es mejor)"
    elif score == 'r2_ajustado':
        p = X.shape[1] 
        # Fórmula vectorizada para ajustar R2
        mean_test_scores = 1 - (1 - mean_test_scores) * (train_sizes_abs - 1) / (train_sizes_abs - p - 1)
        titulo_y = "R2 Ajustado (Mayor es mejor)"
    else:
        titulo_y = f"Score promedio ({score})"

    # 4. Gráfico
    plt.figure(figsize=(8, 5))
    plt.plot(sizes_prop, mean_test_scores, "o--", color="r", label="Validación (CV)")
    
    plt.xlabel("Proporción muestra entrenamiento")
    plt.ylabel(titulo_y)
    plt.title(f"Curva de Aprendizaje - {score.upper()}")
    plt.legend()
    plt.grid(True)
    plt.show()
